---
- name: Provision Elasticsearch Playground
  hosts: elasticsearch
  sudo: yes
  user: root
  roles:
    - role: BashEnvironment
      users: 
        - { homedir: "{{ homedir }}", user: "{{ user }}" }
    - Elasticsearch
